[package]
name = "lr-allthings-red"
version = "0.1.0"
authors = ["Nathaniel <neallred@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0.0"

[build-dependencies]
walkdir = "2.3.1"
